name = "promisance-rogue"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[assets]
directory = "../web/dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "promisance-rogue"
database_id = "b72a4e9d-fdd3-4b2c-984d-425205a42e41"

# Environment variables
[vars]
CORS_ORIGIN = "https://rogue.neopromisance.com,https://promisance-rogue.blake365morgan.workers.dev,http://localhost:3000"

[observability]
[observability.logs]
enabled = false
head_sampling_rate = 1
invocation_logs = true
