name = "promisance-rogue"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[assets]
directory = "../web/dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "promisance-rogue"
database_id = "b72a4e9d-fdd3-4b2c-984d-425205a42e41"
